[1,"=> shiny::runApp()\n\n"]
[2,"Loading required package: shiny\n\nAttaching package: ‘shinydashboard’\n\nThe following object is masked from ‘package:graphics’:\n\n    box\n\n"]
[2,"\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union\n\n"]
[2,"\nAttaching package: ‘DT’\n\nThe following objects are masked from ‘package:shiny’:\n\n    dataTableOutput, renderDataTable\n\n"]
[2,"\nInitialize Python Version 2.7.16 (default, Jun  5 2020, 22:59:21) \n[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-\n\n"]
[1,"R is already connected to Python!\n"]
[2,"Using poppler version 0.73.0\n"]
[1,"Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\n  File \"helper.py\", line 33, in <module>\n\n    \nget_best_match(lst)\n\n  File \"helper.py\", line 3, in get_best_match\n\n    \nimport pandas as pd\n\nImportError\n: \nNo module named pandas\n"]
[2,"Error in pyExecp(sprintf(\"execfile('%s')\", as.character(filename)[1])) : \n  An error has occured while executing Python code. See traceback above.\nCalls: <Anonymous> ... eval -> eval -> ..stacktraceon.. -> pyExecfile -> pyExecp\nExecution halted\n"]
[1,"\nShiny application failed.\n\n"]
